version: '3.0'

services:
  pokemon-api:
    image: pokemon-api
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5432:5432