version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"